### ISSUE TITLE
sunparty's unresolved feedback on GCE survival training

### ISSUE THREAD

**Issue by nkashy1** [GoogleCloudPlatform/ml-on-gcp#14]
This issue is in reference to [this review](https://github.com/GoogleCloudPlatform/ml-on-gcp/pull/11/files/26cc22b508184786e36b33ea36f54b540e6d1d28).

1. Why is worth installing the SDK (prerequisites section)?

1. Custom images - change it to sunparty's recommendation in the review.

1. Delivery mechanism section - see review.

1. Startup scripts - see review.

1. Remove "we will", "we could", etc.

1. Broken link - "our example startup script".

1. Notes and references -- see review.

**Comment by nkashy1** [comment]
"Why is it worth installing the SDK?"

I decided to remove the statement about it being worth installing, as there is already a link to the Cloud SDK page and users can make up their own minds.

**Comment by nkashy1** [comment]
Custom image section change - done

**Comment by nkashy1** [comment]
Delivery mechanism done.

Startup scripts done.

**Comment by nkashy1** [comment]
"we will" -> "we", "We will" -> "We"

**Comment by nkashy1** [comment]
Fixed startup script link

**Comment by nkashy1** [comment]
"Notes and references" section fixed.

**Comment by nkashy1** [comment]
Submitted fixes as [PR 17](https://github.com/GoogleCloudPlatform/ml-on-gcp/pull/17)

**Comment by andrewferlitsch** [comment]
Since a PR was submitted, I am closing this "old" issue.
