### ISSUE TITLE
[gae_serve] time.sleep in _load_model causes gunicode worker to timeout

### ISSUE THREAD

**Issue by Driftwo0d** [GoogleCloudPlatform/ml-on-gcp#15]
When deploying the **gae_serve** example code as is, App Engine responds with a **502 Bad Gateway** error when requesting the root path.

This is caused by the execution of the **_load_model()** function which exceeds the default timeout of gunicorn workers when loading the model from GCS.

At first I tried to increase the timeout by adding `--timeout 60` to the gunicorn command in app.yaml, but then I noticed the **time.sleep(45)** in the **_load_model()** function:

_ml-on-gcp/sklearn/gae_serve/main.py_:
```
@app.before_first_request
def _load_model():
    import time
    time.sleep(45)
   ...
```

Removing this line solved the issue. However I am still curious about why it was here in the first place?
There must be a good reason (:

**Comment by dizcology** [comment]
My apologies: the `sleep` was my experiment and accidentally checked in.  It should be removed (fixed in this [PR](https://github.com/GoogleCloudPlatform/ml-on-gcp/pull/10)).

**Comment by dizcology** [comment]
@Driftwo0d I had the PR merged.  Could you try the updated code and let me know if you run into any issues?
