### ISSUE TITLE
add gae query ml-engine models

### ISSUE THREAD

**Issue by yupbank** [GoogleCloudPlatform/ml-on-gcp#16]
hi, since user can deploy tf models with ml-engine models

while we can use gae to query the ml-engine model, is there a good practice example ?

**Comment by yupbank** [comment]
hi, is there anything going on with this?

**Comment by dizcology** [comment]
Hi @yupbank:  My apologies for the delay.  Does the python code on this page serve your purpose?  [Getting Online Predictions](https://cloud.google.com/ml-engine/docs/online-predict)

**Comment by dizcology** [comment]
@yupbank Could you provide more context on what was not working?  If you deploy a TF model to ml-engine, you should be able to query it from your local machine with the code from the doc.  If this works you should be able to query the same model from inside of GAE.

Or perhaps I misunderstood what you were trying to accomplish.

**Comment by andrewferlitsch** [comment]
please feel free to reopen if the issue still stands.
