### ISSUE TITLE
Add support for testing with minikube

### ISSUE THREAD

**Issue by pmlandwehr** [GoogleCloudPlatform/ml-on-gcp#20]
Hello,

I mentioned this on the GCP slack - I'd be great if there were a simple way to configure `gke_parallel` to be used with minikube for job testing. You can obviously just strip out the invocation of the `GKEParallel` wrapper from your code, but that isn't quite the same thing.

**Comment by dizcology** [comment]
@pmlandwehr My apologies this is way long overdue.  I don't think I will be able to add minikube support for job testing in the near future, so I am closing this issue for now.  Please consider contributing to the tools to add this and/or reopen the issue.
