### ISSUE TITLE
all gcloud commands and files are deprecated in the sklearn part

### ISSUE THREAD

**Issue by edilsonacjr** [GoogleCloudPlatform/ml-on-gcp#27]

**Comment by dizcology** [comment]
@edilsonacjr Could you provide more information about the issue, e.g. pointing us to some of the commands and files which you found to be deprecated?

**Comment by edilsonacjr** [comment]
Most part od gcloud commands.

Em Seg, 21 de mai de 2018 14:43, Yu-Han Liu <notifications@github.com>
escreveu:
