### ISSUE TITLE
Issues deploying app on GCP

### ISSUE THREAD

**Issue by megretson** [GoogleCloudPlatform/ml-on-gcp#28]
Hello! I am continually recieving the following error while trying to deploy this app. I cannot find documentation on the CLOUDSDK_APP_RUNTIME_ROOT. 

_ERROR: (gcloud.app.deploy) Unable to determine the root directory where GAE runtimes are stored.  Please define the CLOUDSDK_APP_RUNTIME_ROOT environment variable._

Is this an issue with how I have downloaded or installed the Cloud SDK? I'd be happy to provide any additional information about the environment I'm using if that would be helpful. Thank you!

**Comment by dizcology** [comment]
@megretson Which app were you trying to deploy?

**Comment by rockmanvnx6** [comment]
Hi, having the same issue here trying to deploy a ReactJS app. Did you manage to fix it? @megretson
