### ISSUE TITLE
Sklearn-Pandas trained ML Pipeline - online prediction on GCP ?

### ISSUE THREAD

**Issue by rafiqhasan** [GoogleCloudPlatform/ml-on-gcp#34]
Hi Team,

I have a very basic requirement on Sklearn Pandas ML pipeline but I am not able to find any clear answer to this problem any where on the documentations. 

Let's say I have an Sklearn pipeline built using Pandas dataframe as input, with pandas functions as transformations etc. So obviously this pipeline will expect a pandas - dataframe during prediction. Does GCMLE already have capability to convert the key value paired JSON payload to Panda-DF during online prediction mode on CMLE ?

Example code:

```
#Transformer functions
def select_col_df(df, cols, iscatego):
    if iscatego == True:
        return df[cols]
    else:
        return df[[cols]]

def calc_grminusirbyvpatd(df):
    df['grminusirbyvpatd'] = ( df['TOTGRQTY'] - df['TOTIRQTY'] ) / df['VPATD']
    return(df[['grminusirbyvpatd']])

def calc_difgrirdbytotgrqty(df):
    def apply_trans(df):
        if not df['TOTGRQTY'] == 0:
            return ( df['DIFGRIRD'] / df['TOTGRQTY'] )
        else:
            return 0
    
    df['difgrirdbytotgrqty'] = df.apply(apply_trans, axis = 1)
    return(df[['difgrirdbytotgrqty']])

#1. Hash convert categorical columns
col_pipe = {}
for c_ in X_train.columns:
    if X_train[c_].dtype == 'object':
#         col_pipe[c_] = Pipeline([
#                                 ('column_selector', CatColSelector(key=c_)),
#                                 ('column_oh', CustomLabelBinarizer())
#                             ])
        
        col_pipe[c_] = Pipeline([
                                    ('col_sel', FunctionTransformer(select_col_df,kw_args={'cols': c_, 'iscatego': True},
                                                                    validate=False)),
                                    ('col_hash', FeatureHasher(n_features=10,input_type='string'))
                                ])
        
#2. Also add numerical columns into pipeline
for c_ in X_train.columns:
    if not X_train[c_].dtype == 'object':
        col_pipe[c_] = Pipeline([
                                ('col_sel', FunctionTransformer(select_col_df,kw_args={'cols': c_, 'iscatego': False},
                                                                validate=False)),
                                ('std_scaler', StandardScaler())
                            ])

#3. Create a few new columns: "grminusirbyvpatd, difgrirdbytotgrqty"
col_pipe['grminusirbyvpatd'] = Pipeline([
                                                ('col_new_1',FunctionTransformer(calc_grminusirbyvpatd, validate=False))
                                            ])

col_pipe['difgrirdbytotgrqty'] = Pipeline([
                                                ('col_new_2',FunctionTransformer(calc_difgrirdbytotgrqty, validate=False))
                                            ])

#4. Combine all features in col_pipe{} with FeatureUnion
feats = FeatureUnion([
                        (col_, col_pipe[col_]) for col_ in list(col_pipe.keys())
                    ])

#5. Add ML algorithm in Pipeline
final_pipeline = Pipeline([
                        ('features',feats),
                        ('classifier', RandomForestClassifier(random_state = 42,n_estimators = 1000,
                                                              oob_score=True,n_jobs=-1,verbose=1)),
                         ])

#6. Train ML model
print("Training ML model")
final_pipeline.fit(X_train, y_train)
```

Seems to be a very basic requirement if we talk about ML on Cloud, any pointers ?

**Comment by rafiqhasan** [comment]
Hi @dizcology 

Thanks a lot for your response and support. 

I may have understood it incorrectly, the API request will be in JSON format and I guess you are referring to converting the JSON to DF before further processing. 

However I see that there will be two issues here:
1. Method df.to_json( ) converts DF to JSON which is opposite and will not convert API JSON payload to DF
2. Even if we add a step to achieve the above, I believe only those functions can be included in SKLearn pipelines which have been provided in sklearn package: http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline . It may not be possible to directly include Pandas functions in sklearn pipelines directly until Pandas is imported specifically before executing the pipeline. 

If we include DF functions( external library ) in SKLearn pipeline, will it execute when the model is deployed on GCP MLE ?

**Comment by dizcology** [comment]
I meant for the client to call df.to_json prior to sending data to the service, that way you would still be able to send a json.

Alternatively, you might be able to serialize the whole dataframe into a string (perhaps csv?), and have the first step of your pipeline de-serialize it.  Similar to how images are often sent in the base64 encoded format?

The issue with dataframes is that they are rather complex python objects that one way or another need to be encoded as a stream of bytes of some sort to be sent to the prediction service; http does not understand what a dataframe is.

**Comment by rafiqhasan** [comment]
Hi @dizcology

Thanks a lot for responding back !

I think you misunderstood the query. We are fine with sending the JSON to REST API and then process it.( we alread have a function in pipeline to convert JSON to DF ). 

Now our query is around the capability of GCP MLE to run Pandas library functions internally.

Our query is: If we have certain Pandas related function **embedded in the SKLearn pipeline** for example, df.sum( ) or df.concat( ) and export the pipeline as .PKL file, then when this model is deployed on GCP MLE, will GCMLE be able to execute those pandas function internally. Does the GCP MLE internally support execution of pandas functions as well or only SkLearn pipeline functions ?

Will the GCMLE platform internally not throw an error like "**PD not defined**" if such a pipeline is executed ?

**Comment by dizcology** [comment]
@rafiqhasan 

It's been a while and I am not sure if you have already found a way around the potential issues of running pandas functions in a sklearn pipeline in prediction.  AI Platform Prediction now offers more flexible ways of deploying sklearn pipelines for prediction: https://cloud.google.com/ml-engine/docs/scikit/custom-prediction-routines

**Comment by rafiqhasan** [comment]
Wow , I never knew this would actually come up as a new feature 👍 

After reading at: https://cloud.google.com/ml-engine/docs/scikit/custom-prediction-routine-scikit-learn 

I guess things should get easier here. So do you think below steps would work:
1. Export the complete SkLearnPipeline object as .pkl( includes model + pre-processing function in same file )
2. In setup.py specify the package dependency for Pandas

There is one catch here though which I am still not sure, we have a single model.pkl file with the complete SkLearn pipeline object( includes the pre-processing + prediction function together). 

So the from_path( ) function in predictor.py would load the model.pkl and pre-process will not be a separate function.

**Comment by dizcology** [comment]
@rafiqhasan I don't think `preprocess` has to be a separate function.  Could you try your configuration and let us know if it works?

**Comment by andrewferlitsch** [comment]
There has been no response from submitter for 1/2 year.
